### ISSUE TITLE
Create level start state

### ISSUE THREAD

**Issue by KwenaMashamaite** [KwenaMashamaite/SuperPacMan#1]
#### Description
This state is displayed before a new level is started or when the current level restarts after Pacman dies

#### Tasks

- [x] Display the current level
- [x] Display the current level fruit with its associated points
- [x] Display the player score
- [x] Display the current high score
- [ ] Display the current number of player lives
