### ISSUE TITLE
Make Pacman respond to keyboard inputs

### ISSUE THREAD

**Issue by KwenaMashamaite** [KwenaMashamaite/SuperPacMan#13]
#### Tasks
- [x] Pacman goes to the left when left arrow key is pressed
- [x] Pacman goes to the right when right arrow key is pressed
- [x] Pacman goes up when up arrow key is pressed
- [x] Pacman goes down when down arrow key is pressed
