### ISSUE TITLE
Add ghosts to intro state

### ISSUE THREAD

**Issue by KwenaMashamaite** [KwenaMashamaite/SuperPacMan#5]
#### Description

These ghosts chase Pacman after he successfully unlocks the doors and eats the fruits inside.
The ghosts don't show themselves until Pacman is on his way to eat a Power Pellet.

This issue depends on #3 

#### Tasks

- [x] Ghosts turn blue after Pacman eats a power pellet
- [x] Pacman eats all the four ghosts after he eats a power pellet and switches direction
- [x] After eating the ghosts, Pacman disappears into the side of the screen
- [x] After a short duration Pacman reappears on the screen, once again being chased by ghosts
- [x] Pacman eats a super pellet the second time he's chased by the ghosts; he enlarges and they they flatten while
- [x] Pacman reverses direction while the ghosts continue in the same direction with neither the the ghost or Pacman dying
- [x] After all entities disappear from he screen, the  game switches to main menu state
