### ISSUE TITLE
Add chase state

### ISSUE THREAD

**Issue by KwenaMashamaite** [KwenaMashamaite/SuperPacMan#7]
#### Description

In this state ghosts chase Pacman using different chase strategies:

1. _``Aggressive``_ - Ghost aggressively chases Pacman by following him and taking the shortest path to him

2. _``Ambush``_ - Ghost attempts to ambush Pacman by approaching him from the front 

3. _``Random``_ - Ghost randomly moves in the grid

#### Tasks

- [ ] Blinky (red ghost) aggressively chases Pacman
- [ ] Pinky (pink ghost) and Inky (orange ghost) ambushes Pacman
- [ ] Clyde randomly chases Pacman
